In [2]:
import pandas as pd

In [6]:
df1=pd.read_csv(r'C:\Users\india\OneDrive - Chandigarh University\Desktop\resume new\clients  pro\online fraud recuriement detection system\trail 1\fake_job_postings.csv', engine='python')
df1.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [7]:
df1.shape

(17880, 18)

In [8]:
df=df1[['description','requirements','fraudulent']]
df.head()

,description,requirements,fraudulent
0,"Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,0
1,Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,0
2,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,0
3,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",0
4,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,0

In [9]:
###Drop Nan Values
df=df.dropna()

In [10]:
df.shape

(15184, 3)

In [11]:
## Get the Independent Features

X=df.drop('fraudulent',axis=1)

In [12]:
## Get the Dependent features
y=df['fraudulent']

In [13]:
y.value_counts()

fraudulent
0    14472
1      712
Name: count, dtype: int64

In [16]:
import tensorflow as tf
tf.__version__

ImportError: Traceback (most recent call last):
  File "c:\Users\india\anaconda3\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 73, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [ ]:
voc_size=5000

## Onehot Representation:

In [15]:
message = X.copy()

In [16]:
message['description'][1]

"Organised - Focused - Vibrant - Awesome!Do you have a passion for customer service? Slick typing skills? Maybe Account Management? ...And think administration is cooler than a polar bear on a jetski? Then we need to hear you!\xa0We are the Cloud Video Production Service and opperating on a glodal level. Yeah, it's pretty cool. Serious about\xa0delivering a world class product and excellent customer service.Our rapidly expanding business is looking for a talented Project Manager to manage the successful delivery of video projects, manage client communications and drive the production process. Work with some of the coolest brands on the planet and learn from a global team that are representing NZ is a huge way!We are entering the next growth stage of our business and growing quickly internationally. \xa0Therefore, the position is bursting with opportunity for the right person entering the business at the right time.\xa090 Seconds, the worlds Cloud Video Production Service -\xa0http://90#URL_fbe6559afac620a3cd2c22281f7b8d0eef56a73e3d9a311e2f1ca13d081dd630#90 Seconds is the worlds Cloud Video Production Service enabling brands and agencies to get high quality online video content shot and produced anywhere in the world. Fast, affordable, and all managed seamlessly in the cloud from purchase to publish.\xa090 Seconds removes the hassle, cost, risk and speed issues of working with regular video production companies by managing every aspect of video projects in a beautiful online experience. \xa0With a growing network of over 2,000 rated video professionals in over 50 countries and dedicated production success teams in 5 countries guaranteeing video project success 100%. It's as easy as commissioning a quick google adwords campaign.90 Seconds has produced almost 4,000 videos in over 30 Countries for over 500 Global brands including some of the worlds largest including Paypal, L'oreal, Sony and Barclays and has offices in Auckland, London, Sydney, Tokyo &amp; Singapore.Our Auckland office is based\xa0right in the heart of the Wynyard Quarter Innovation Precinct - GridAKL!\xa0"

In [17]:
message.reset_index(inplace=True)

In [18]:
import nltk
import re
from nltk.corpus import stopwords

In [20]:
from nltk.stem.porter import PorterStemmer
import nltk
nltk.download('stopwords')
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['description'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [21]:
corpus[1]

'organis focus vibrant awesom passion custom servic slick type skill mayb account manag think administr cooler polar bear jetski need hear cloud video product servic opper glodal level yeah pretti cool seriou deliv world class product excel custom servic rapidli expand busi look talent project manag manag success deliveri video project manag client commun drive product process work coolest brand planet learn global team repres nz huge way enter next growth stage busi grow quickli intern therefor posit burst opportun right person enter busi right time second world cloud video product servic http url fbe afac cd c f b eef e e f ca dd second world cloud video product servic enabl brand agenc get high qualiti onlin video content shot produc anywher world fast afford manag seamlessli cloud purchas publish second remov hassl cost risk speed issu work regular video product compani manag everi aspect video project beauti onlin experi grow network rate video profession countri dedic product success team countri guarante video project success easi commiss quick googl adword campaign second produc almost video countri global brand includ world largest includ paypal l oreal soni barclay offic auckland london sydney tokyo amp singapor auckland offic base right heart wynyard quarter innov precinct gridakl'

In [23]:
voc_size=5000
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr[1]

[3070,
 1109,
 1241,
 3006,
 315,
 3179,
 4923,
 2243,
 2996,
 448,
 4600,
 2101,
 2397,
 482,
 2002,
 1437,
 3485,
 115,
 57,
 3674,
 4073,
 4725,
 4805,
 1661,
 4923,
 859,
 635,
 3862,
 545,
 4108,
 3563,
 2277,
 2415,
 654,
 1914,
 1661,
 4467,
 3179,
 4923,
 3791,
 1918,
 3769,
 22,
 4568,
 737,
 2397,
 2397,
 3374,
 3176,
 4805,
 737,
 2397,
 2662,
 290,
 1462,
 1661,
 3940,
 1714,
 2273,
 3286,
 72,
 1674,
 1545,
 2965,
 4341,
 2302,
 1299,
 2901,
 3934,
 908,
 2069,
 4429,
 3769,
 3390,
 3905,
 4812,
 647,
 4040,
 2234,
 2981,
 684,
 2675,
 3934,
 3769,
 684,
 3262,
 2379,
 654,
 4725,
 4805,
 1661,
 4923,
 941,
 3849,
 3064,
 4532,
 4872,
 2580,
 3330,
 698,
 2722,
 101,
 101,
 3330,
 2666,
 1630,
 2379,
 654,
 4725,
 4805,
 1661,
 4923,
 144,
 3286,
 3910,
 100,
 1193,
 2148,
 92,
 4805,
 4371,
 404,
 2302,
 4390,
 654,
 1605,
 4997,
 2397,
 3176,
 4725,
 3852,
 4979,
 2379,
 3649,
 565,
 663,
 4501,
 2240,
 2514,
 1714,
 127,
 4805,
 1661,
 190,
 2397,
 333,
 573,
 4805,
 737,
 3710,
 92,
 1759,
 3390,
 2969,
 3850,
 4805,
 2637,
 3175,
 2007,
 1661,
 3374,
 2965,
 3175,
 2853,
 4805,
 737,
 3374,
 3640,
 868,
 4486,
 1799,
 4463,
 2174,
 2379,
 2302,
 4050,
 4805,
 3175,
 1545,
 3286,
 4911,
 654,
 4697,
 4911,
 3258,
 4970,
 4791,
 1187,
 3751,
 3751,
 254,
 290,
 4430,
 3800,
 2391,
 498,
 254,
 3751,
 2853,
 684,
 650,
 1941,
 935,
 4927,
 4327,
 1979]

## Embedding Representation:

In [24]:
sent_length=40
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[4897 4371 2397 ... 3821  796 2461]
 [3374 3640  868 ... 4927 4327 1979]
 [   0    0    0 ... 1454 4729 4172]
 ...
 [3262 3647  568 ... 3835  427 1027]
 [2043 2826 2861 ... 1103 1799 3830]
 [2070   39 1714 ...   68 4890 4014]]

In [25]:
embedded_docs[0]

array([4897, 4371, 2397, 2253,  137, 3396, 1127, 4120, 1301,   10, 4470,
       4470, 1301, 2540,  546, 4830, 1301, 4993, 1301, 4144, 2667, 2391,
        812, 1151, 3751, 2002, 1714,  599,   44,  700,  103, 2885, 2677,
       1558, 3879,  568, 4688, 3821,  796, 2461], dtype=int32)

In [26]:
## Creating model
embedding_vector_features=50
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100))) ##Just add bidirectional!!, except it would just behave as normal LSTM Model
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [27]:
len(embedded_docs),y.shape

(4948, (4948,))

In [28]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [29]:
X_final[1]

array([3374, 3640,  868, 4486, 1799, 4463, 2174, 2379, 2302, 4050, 4805,
       3175, 1545, 3286, 4911,  654, 4697, 4911, 3258, 4970, 4791, 1187,
       3751, 3751,  254,  290, 4430, 3800, 2391,  498,  254, 3751, 2853,
        684,  650, 1941,  935, 4927, 4327, 1979], dtype=int32)

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.25, random_state=32)

In [32]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=12,batch_size=64)

Epoch 1/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 15s 103ms/step - accuracy: 0.9221 - loss: 0.3872 - val_accuracy: 0.9636 - val_loss: 0.1563
Epoch 2/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 7s 122ms/step - accuracy: 0.9529 - loss: 0.1873 - val_accuracy: 0.9636 - val_loss: 0.1505
Epoch 3/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 5s 94ms/step - accuracy: 0.9604 - loss: 0.1465 - val_accuracy: 0.9693 - val_loss: 0.1156
Epoch 4/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 10s 95ms/step - accuracy: 0.9788 - loss: 0.0729 - val_accuracy: 0.9741 - val_loss: 0.1164
Epoch 5/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 11s 103ms/step - accuracy: 0.9924 - loss: 0.0396 - val_accuracy: 0.9725 - val_loss: 0.1239
Epoch 6/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 7s 121ms/step - accuracy: 0.9937 - loss: 0.0249 - val_accuracy: 0.9733 - val_loss: 0.1445
Epoch 7/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 9s 95ms/step - accuracy: 0.9942 - loss: 0.0208 - val_accuracy: 0.9733 - val_loss: 0.1481
Epoch 8/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 7s 124ms/step - accuracy: 0.9941 - loss: 0.0145 - val_accuracy: 0.9757 - val_loss: 0.1540
Epoch 9/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 6s 112ms/step - accuracy: 0.9975 - loss: 0.0064 - val_accuracy: 0.9701 - val_loss: 0.1577
Epoch 10/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 9s 97ms/step - accuracy: 0.9967 - loss: 0.0098 - val_accuracy: 0.9717 - val_loss: 0.1789
Epoch 11/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 7s 120ms/step - accuracy: 0.9980 - loss: 0.0099 - val_accuracy: 0.9741 - val_loss: 0.1703
Epoch 12/12
58/58 ━━━━━━━━━━━━━━━━━━━━ 5s 94ms/step - accuracy: 0.9991 - loss: 0.0035 - val_accuracy: 0.9741 - val_loss: 0.1714

## Model Performance and Accuracy:

In [34]:
y_pred = (model1.predict(X_test) > 0.5).astype("int32")

39/39 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

In [35]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1189,    3],
       [  29,   16]])

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9741309620048505

In [37]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99      1192
         1.0       0.84      0.36      0.50        45

    accuracy                           0.97      1237
   macro avg       0.91      0.68      0.74      1237
weighted avg       0.97      0.97      0.97      1237

In [ ]:
import pickle
# Load the saved model
with open('model.pkl', 'rb') as file:
    model = pickle.load(file)
print("Model loaded successfully!")